<a href="https://colab.research.google.com/github/diegogameroc/Python-Practica/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Sección nueva

In [ ]:

help(np.array)

In [ ]:
ListaData = [12,32,345,36,45,35,342,34,123,12,43]
vec1 = np.array(ListaData)

In [ ]:
import random as rnd
edades=[]

for i in range(10000):
    edades.append(rnd.randint(0,120))

In [ ]:
#ndarray es un iterable: Mostremos las edadee que son numero pared

for elemento in edades:
    if elemento % 2 == 0:
        print(edades)

In [9]:
x = np.random.laplace(loc=12.3,scale=3.14,size=10000)
M = np.random.laplace(loc=12.3,scale=3.14,size=(10**2,10**2))
D = np.random.laplace(loc=12.3,scale=3.14,size=(3,3,3))

In [6]:
# Atributo ndim : numero de dimensiones
x.ndim

1

In [10]:
# Atributo ndim : numero de dimensiones
M.ndim

2

In [11]:
# Atributo ndim : numero de dimensiones
D.ndim

3

In [12]:
# Acceso a la 5ta columna de M: Objeto bidimensional
M[:,4]

array([14.16346043, -1.74801505, 15.35343066, 10.13847833, 10.03826183,
        9.13716855, 15.30927595, 10.80524518, 12.31395143, 13.25065591,
       16.50686428, 14.63307915, 11.72027037, 13.91903245, 11.15821685,
        9.63296272, 16.19596142,  9.0345627 , 19.31489887, 13.20979067,
       12.11425677, 11.62672602, 10.86189186, 11.96797967, 11.77459581,
       13.18697026, 10.23076609, 12.1923193 ,  8.01326802, 13.03405089,
       14.19565452,  9.57218959, 10.00409062, 12.98341629,  2.55887735,
        2.24703102,  9.06726409, 14.71865331, 16.23312735,  7.27052051,
       14.45021611,  7.38489437, 12.28745933, 12.55052958,  7.87476821,
       14.15086656, 11.72292652, 10.29778387,  8.10393593, 13.51222694,
       22.68975283, 13.0219907 , 13.24144367,  9.30376581,  6.73856189,
       12.68881542, 13.00839389, 10.24336923, 14.05679399, 15.6379088 ,
       15.0916504 , 11.83806104, 15.48208833,  6.77999375, 16.90780584,
       15.28121626, 12.28222778,  6.58300722, 11.1497122 , 12.33

In [ ]:
# Acceso a la 5ta columna de M: Objeto bidimensional
M[:,4]

array([14.16346043, -1.74801505, 15.35343066, 10.13847833, 10.03826183,
        9.13716855, 15.30927595, 10.80524518, 12.31395143, 13.25065591,
       16.50686428, 14.63307915, 11.72027037, 13.91903245, 11.15821685,
        9.63296272, 16.19596142,  9.0345627 , 19.31489887, 13.20979067,
       12.11425677, 11.62672602, 10.86189186, 11.96797967, 11.77459581,
       13.18697026, 10.23076609, 12.1923193 ,  8.01326802, 13.03405089,
       14.19565452,  9.57218959, 10.00409062, 12.98341629,  2.55887735,
        2.24703102,  9.06726409, 14.71865331, 16.23312735,  7.27052051,
       14.45021611,  7.38489437, 12.28745933, 12.55052958,  7.87476821,
       14.15086656, 11.72292652, 10.29778387,  8.10393593, 13.51222694,
       22.68975283, 13.0219907 , 13.24144367,  9.30376581,  6.73856189,
       12.68881542, 13.00839389, 10.24336923, 14.05679399, 15.6379088 ,
       15.0916504 , 11.83806104, 15.48208833,  6.77999375, 16.90780584,
       15.28121626, 12.28222778,  6.58300722, 11.1497122 , 12.33

In [13]:
D[:,:,0]

array([[10.7995144 , 15.87090383, 14.38993764],
       [ 7.82427326, 12.40911805,  6.98749102],
       [10.74057023,  9.53242187, 12.78364109]])

In [15]:
#Atributo Size
x.size


10000

In [16]:
M.size

10000

In [17]:
D.size

27

In [18]:
# Atributo dtype : tipo de dato de cada elemento del objeto ndarray
x.dtype

dtype('float64')

In [19]:
# Atributo dtype : tipo de dato de cada elemento del objeto ndarray
x.dtype, M.dtype, D.dtype

(dtype('float64'), dtype('float64'), dtype('float64'))

In [23]:
#atributo shape
x.shape,M.shape,D.shape

((10000,), (100, 100), (3, 3, 3))

In [24]:
# Atributo itemsize : Numero de bytes de cada elemento en el objeto de tipo ndarray
x.itemsize,M.itemsize,D.itemsize

(8, 8, 8)

In [ ]:
dir(M)

In [ ]:
# Aprender a utilizar cada uno de los metodos de interes que se puede aplicar
# a un dato de tipo ndarray


In [31]:
#Carguemos el modulo time para tomar el timepo que se demora un calculo
import time
#Benchmark (TEST DE STRESS) sobre numeros enteros
for tipo_entero in [np.int8, np.int16,np.int32,np.int64]:
  # Inciiamos un cronometro
  t0 = time.time()
  #Desarrollamos una operacion matematica
  sum(np.random.randint(0,120,size=10**7,dtype=tipo_entero))
  #detenemos el cronometro
  tf = time.time()

  print("Tipo de entero ",tipo_entero)
  print("Tiempo de procesamiento ",tf-t0)
  print("*"*100)

Tipo de entero  <class 'numpy.int8'>
Tiempo de procesamiento  1.8374698162078857
****************************************************************************************************
Tipo de entero  <class 'numpy.int16'>
Tiempo de procesamiento  2.326037883758545
****************************************************************************************************
Tipo de entero  <class 'numpy.int32'>
Tiempo de procesamiento  2.70991587638855
****************************************************************************************************
Tipo de entero  <class 'numpy.int64'>
Tiempo de procesamiento  0.948540210723877
****************************************************************************************************


In [ ]:
for tipo_float in [np.float32, np.float64, np.float128]:
    t0 = time.time()
    # Desarrollo una operacion sencilla del algebra lineal : Calcular la inversa de una matriz
    np.linalg.inv(np.array(np.random.chisquare(9, (10**4, 10**4)), dtype=tipo_float))
    tf = time.time()
    print("Tipo de punto flotante :", tipo_float)
    print("Tiempo de procesamiento ", tf - t0)
    print("*" * 100)
